# CoffeeGuard AI — Kaggle GPU training kernel (generated by `coffeeguard remote train`).
# It installs the project wheel from the private code dataset, links the processed image
# dataset into a project-shaped working dir, and runs the normal CLI for each job.
import glob
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

JOBS = json.loads("""__JOBS__""")

INPUT = Path("/kaggle/input")
WORK = Path("/kaggle/working")


def find_one(pattern: str) -> Path:
    hits = sorted(glob.glob(str(INPUT / "**" / pattern), recursive=True))
    if not hits:
        raise FileNotFoundError(f"{pattern} not found under {INPUT}")
    return Path(hits[0])


def sh(*cmd: str) -> None:
    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True)


wheel = find_one("coffee_guard_ai-*.whl")
sh(sys.executable, "-m", "pip", "install", "-q", "--no-deps", str(wheel))
sh(
    sys.executable,
    "-m",
    "pip",
    "install",
    "-q",
    "timm>=1.0.9",
    "pydantic>=2.7",
    "typer>=0.12",
    "pyyaml>=6.0",
)

code_root = wheel.parent
for sub in ("configs", "data/splits"):
    src = code_root / sub
    dst = WORK / sub
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
(WORK / "pyproject.toml").write_text("[project]\nname='kaggle-run'\n")  # marks project root

processed = find_one("PROCESSED_MARKER").parent
(WORK / "data").mkdir(exist_ok=True)
link = WORK / "data" / "processed"
if link.exists() or link.is_symlink():
    link.unlink()
link.symlink_to(processed, target_is_directory=True)

os.chdir(WORK)
os.environ["COFFEEGUARD_ROOT"] = str(WORK)
sh("nvidia-smi")
for job in JOBS:
    cmd = [
        "coffeeguard",
        "train",
        "-c",
        job["config"],
        "--seed",
        str(job["seed"]),
        "--set",
        f"runs_dir={WORK / 'runs'}",
    ]
    for override in job.get("overrides", []):
        cmd += ["--set", override]
    sh(*cmd)

# keep only what we need in the output (runs/), drop the copied inputs
for sub in ("configs", "data"):
    shutil.rmtree(WORK / sub, ignore_errors=True)
print("ALL JOBS DONE", flush=True)
